import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import crypto from 'crypto';

/** Merge Tailwind CSS classes with conflict resolution */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/** Generate SHA-256 hash of content for caching */
export function hashContent(content: string): string {
  return crypto.createHash('sha256').update(content).digest('hex');
}

/** Format file size in human-readable form */
export function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}

/** Format date in human-readable form */
export function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

/** Format relative time (e.g., '2 hours ago') */
export function formatRelativeTime(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMins / 60);
  const diffDays = Math.floor(diffHours / 24);

  if (diffMins < 1) return 'Just now';
  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;
  return formatDate(dateString);
}

/** Truncate text with ellipsis */
export function truncateText(text: string, maxLength: number = 200): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength).trim() + '...';
}

/** Validate file type for upload */
export function isValidFileType(fileName: string): boolean {
  const validExtensions = ['.pdf', '.docx', '.txt'];
  const ext = fileName.toLowerCase().slice(fileName.lastIndexOf('.'));
  return validExtensions.includes(ext);
}

/** Get file extension from filename */
export function getFileExtension(fileName: string): string {
  return fileName.slice(fileName.lastIndexOf('.') + 1).toLowerCase();
}

/** Maximum file size: 20MB */
export const MAX_FILE_SIZE = 20 * 1024 * 1024;

/** Legal disclaimer text */
export const LEGAL_DISCLAIMER = 'This analysis is generated by AI and is for informational purposes only. It does not constitute legal advice. Please consult a qualified legal professional for specific legal matters.';

/** Document type labels */
export const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  contract: 'Contract',
  agreement: 'Agreement',
  policy: 'Policy',
  tos: 'Terms of Service',
  nda: 'Non-Disclosure Agreement',
  lease: 'Lease Agreement',
  employment: 'Employment Contract',
  other: 'Other',
};

/** Risk level colors */
export const RISK_COLORS = {
  low: { bg: 'bg-green-100', text: 'text-green-800', border: 'border-green-300' },
  medium: { bg: 'bg-yellow-100', text: 'text-yellow-800', border: 'border-yellow-300' },
  high: { bg: 'bg-red-100', text: 'text-red-800', border: 'border-red-300' },
} as const;
