import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export default function TermsOfServicePage() {
  return (
    <div className="flex min-h-screen flex-col bg-gray-50">
      <Header />
      <main className="flex-1 container-custom py-16">
        <div className="max-w-3xl mx-auto bg-white p-8 md:p-12 rounded-2xl border border-gray-200 shadow-sm">
          <h1 className="text-3xl font-extrabold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500 mb-8">Last Updated: September 2026</p>

          <div className="space-y-6 text-gray-700 text-sm leading-relaxed">
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 text-amber-900 text-sm font-medium">
              <strong>Crucial Notice:</strong> LegalLens is an automated software application powered by artificial intelligence. It does NOT provide legal advice and is NOT a law firm. Using LegalLens does not create an attorney-client relationship.
            </div>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-2">1. Informational Purpose Only</h2>
              <p>
                The simplifications, risk assessments, comparisons, checklists, and chat responses generated by LegalLens are for informational and educational purposes only. They are intended to assist you in preparing for discussions with qualified legal counsel, not to substitute for professional legal review.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-2">2. User Responsibilities & Acceptable Use</h2>
              <p>
                You agree not to upload any unlawful material, malicious code, or documents containing trade secrets or classified information that you do not have authorization to process.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-2">3. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by applicable law, LegalLens and its developers shall not be liable for any indirect, consequential, punitive, or reliance damages resulting from your use of or reliance upon AI-generated analysis.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-2">4. Modifications to the Service</h2>
              <p>
                We reserve the right to update or modify features, models, or terms at any time. Continued use of the platform constitutes acceptance of revised terms.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
